---
- name: Install apt key
  get_url:
    url: https://weechat.org/dev/info/debian_repository_signing_key/
    dest: /etc/apt/trusted.gpg.d/weechat.gpg
  become: true

- name: Install apt repository
  apt_repository:
    repo: 'deb https://weechat.org/ubuntu {{ ansible_distribution_release }} main'
    state: present
    filename: "weechat"
    update_cache: yes
  become: true

- name: Install weechat
  apt:
    name:
      - weechat-curses
      - weechat-plugins
      - weechat-python
      - weechat-perl
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Make local bin dir
  file:
    path: '~/bin'
    state: directory

- name: Add irc script
  copy:
    src: irc
    dest: '~/bin/irc'
    mode: '0755'
