- name: Remove unwanted packages
  apt:
    name:
      - landscape-client
      - landscape-common
      - whoopsie
      - update-notifier-common
      - ubuntu-release-upgrader-core
      - resolvconf
      - python2
      - python
    state: absent

- name: Install common packages
  apt:
    name:
      - git
      - python3
      - python3-pip
      - vim-nox
      - ntp
      - screen
      - curl
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- name: Make sure ntp is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes

- name: Get editor alternatives
  command: update-alternatives --query editor
  register: editor_current
  changed_when: false

- name: Set vim-nox as the default editor
  command: update-alternatives --set editor {{ editor }}
  when: editor_current.stdout_lines|select('match', 'Value:')|first|split|last != editor
  vars:
    editor: /usr/bin/vim.nox

- name: Install pip
  shell: curl -s https://bootstrap.pypa.io/get-pip.py | python3
  args:
    creates: /usr/local/bin/pip3

- name: Update python modules from pypi
  pip:
    name:
      - setuptools
      - pip
      - virtualenvwrapper
      - ipython
    state: latest
