---
- hosts: ansibledev
  roles:
    - import_role:
        role:
          name: mosh
      tags:
        - mosh
      become: true

    - import_role:
        role:
          name: docker
          docker_users:
            - sivel
      tags:
        - docker
      become: true

    - import_role:
        role:
          name: pydev
      tags:
        - pydev

    - import_role:
        role:
          name: pyenv
      tags:
        - pyenv

    - import_role:
        role:
          name: ansibledev
      tags:
        - ansibledev

    - import_role:
        role:
          name: powerline-shell
      tags:
        - powerline_shell

    - import_role:
        role:
          name: bistory
      tags:
        - bistory
