---
- hosts: ansibledev
  tasks:
    - import_role:
        role:
          name: mosh
      tags:
        - mosh
      become: true

    - include_role:
        role:
          name: docker
          docker_users:
            - sivel
        apply:
          become: true
          tags:
            - docker
      tags:
        - docker
      when: docker|default(True)|bool

    - import_role:
        role:
          name: pydev
      tags:
        - pydev

    - import_role:
        role:
          name: pyenv
      tags:
        - pyenv

    - import_role:
        role:
          name: ansibledev
      tags:
        - ansibledev

    - import_role:
        role:
          name: powerline-shell
      tags:
        - powerline_shell

    - import_role:
        role:
          name: bistory
      tags:
        - bistory

    - import_role:
        role:
          name: caddy_v2
          caddyfile: "{{ playbook_dir }}/files/ansibledev/Caddyfile.v2"
      become: true
      tags:
        - caddy
