---
- hosts: all:!esx
  become: true
  tasks:
    - import_role:
        role:
          name: hostname
      tags:
        - hostname

    - import_role:
        role:
          name: dns
      tags:
        - dns

    - import_role:
        role:
          name: timezone
      tags:
        - timezone

    - import_role:
        role:
          name: users
      tags:
        - users

    - import_role:
        role:
          name: common-packages
      tags:
        - common-packages

    - include_role:
        role:
          name: interfaces
        apply:
          tags:
            - interfaces
      when: manage_interfaces|default(False)|bool
      tags:
        - interfaces

    - import_role:
        role:
          name: openssh
          opensshd_PermitRootLogin: "no"
          opensshd_PasswordAuthentication: "no"
          opensshd_UseDNS: "no"
      tags:
        - openssh

    - import_role:
        role:
          name: cleanup
      tags:
        - cleanup
