---
- hosts: all
  become: true
  roles:
    - role: hostname
      tags:
        - hostname

    - role: dns
      tags:
        - dns

    - role: timezone
      tags:
        - timezone

    - role: users
      tags:
        - users

    - role: common-packages
      tags:
        - common-packages

    - role: interfaces
      when: manage_interfaces|default(False)|bool
      tags:
        - interfaces

    - role: openssh
      opensshd_PermitRootLogin: "no"
      opensshd_PasswordAuthentication: "no"
      opensshd_UseDNS: "no"
      tags:
        - openssh

    - role: cleanup
      tags:
        - cleanup
