- name: Reboot ESXi server
  hosts: esx
  gather_facts: false
  tasks:
    - name: List running vms
      command: esxcli vm process list
      register: process_list
      changed_when: false

    - name: Power off VMs
      command: "esxcli vm process kill --type=soft --world-id={{ item }}"
      loop: "{{ process_list.stdout_lines|select('search', 'World ID')|map('replace', '   World ID: ', '')|list }}"

    - name: Put server into maintenance mode
      command: esxcli system maintenanceMode set --enable true
      register: maintenance_mode
      failed_when: maintenance_mode.rc != 0 and maintenance_mode.stdout != 'Maintenance mode is already enabled.'
      changed_when: maintenance_mode.rc == 0

    - name: Reboot host
      reboot:

    - name: Pause for good measure
      pause:
        seconds: 30

    - name: Disable maintenance mode
      command: esxcli system maintenanceMode set --enable false

    - name: List all VMs
      command: vim-cmd vmsvc/getallvms
      register: all_vms

    - name: Power on VMs
      command: "vim-cmd vmsvc/power.on {{ item.split()|first }}"
      loop: "{{ all_vms.stdout_lines[1:] }}"
      loop_control:
        label: "{{ item.split()|first }}"
