- hosts: vivo
  gather_facts: false
  vars:
    distros:
      centos_stream8:
        url: https://cloud.centos.org/centos/8-stream/x86_64/images/
      centos_stream9:
        url: https://cloud.centos.org/centos/9-stream/x86_64/images/
      fedora35:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/
      ubuntu2004:
        url: https://cloud-images.ubuntu.com/focal/current/
        prefix: ubuntu-
      debian11:
        url: https://cloud.debian.org/images/cloud/bullseye/latest/
      arch:
        url: https://mirror.pkgbuild.com/images/latest/
      freebsd13:
        url: '{{ bsd_cloud_image }}/images/freebsd/13.0/freebsd-13.0-zfs.qcow2'
      netbsd9:
        url: '{{ bsd_cloud_image }}/images/netbsd/9.2/2021-12-11/netbsd-9.2.qcow2'
      openbsd7:
        url: '{{ bsd_cloud_image }}/images/openbsd/7.0/2021-12-11/openbsd-7.0.qcow2'
      dragonflybsd6:
        url: '{{ bsd_cloud_image }}/images/dragonflybsd/6.0.0/dragonflybsd-6.0.0-hammer2.qcow2'
    regex: '[\w\.-]+(?:genericcloud|cloudimg|cloud-base)[\w\.-]+(?:\.qcow2|(?<!disk-kvm)\.img)'
    bsd_cloud_image: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org
  tasks:
    - delegate_to: localhost
      when: item.1.url|default(item.0.1.url)|splitext|last != ".qcow2"
      block:
        - uri:
            url: '{{ item.1.url }}'
            return_content: true
          loop: '{{ distros|dictsort }}'
          register: checksums

        - set_fact:
            'img_url_{{ item.0.0 }}':
                src: '{{ [base|trim("/"), latest]|join("/") }}'
                dest: '{{ item.0.1.prefix|default("") ~ latest|splitext|first }}.qcow2'
          vars:
            base: '{{ item.0.1.url if item.0.1.url|last == "/" else item.0.1.url|dirname }}'
            sixfour: '{{ item.1.content.splitlines()|select("search", "(amd64|x86_64)", ignorecase=true)|join("\n") }}'
            latest: '{{ sixfour|regex_findall(regex, ignorecase=true)|sort|last|regex_replace("\*", "") }}'
          loop: '{{ distros|dictsort|zip(checksums.results) }}'
          loop_control:
            label: '{{ item.0 }}'

    - set_fact:
        'img_url_{{ item.0 }}':
          src: '{{ item.1.url }}'
          dest: '{{ item.1.url|basename }}'
      when: item.1.url|splitext|last == ".qcow2"
      loop: '{{ distros|dictsort }}'

    - get_url:
        url: '{{ item.src }}'
        dest: /mnt/data/cloudimg/{{ item.dest }}
      loop: '{{ q("vars", *q("varnames", "^img_url_.+")) }}'
