- hosts: vivo
  gather_facts: false
  vars:
    distros:
      centos_stream8:
        url: https://cloud.centos.org/centos/8-stream/x86_64/images/
      centos_stream9:
        url: https://cloud.centos.org/centos/9-stream/x86_64/images/
      fedora35:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/
      ubuntu2004:
        url: https://cloud-images.ubuntu.com/focal/current/
        prefix: ubuntu-
      debian11:
        url: https://cloud.debian.org/images/cloud/bullseye/latest/
      arch:
        url: https://mirror.pkgbuild.com/images/latest/
    regex: '[\w\.-]+(?:genericcloud|cloudimg|cloud-base)[\w\.-]+(?:\.qcow2|(?<!disk-kvm)\.img)'
  tasks:
    - delegate_to: localhost
      block:
        - uri:
            url: '{{ item.1.url }}'
            return_content: true
          loop: '{{ distros|dictsort }}'
          register: checksums

        - set_fact:
            'img_url_{{ item.0.0 }}':
                src: '{{ [base|trim("/"), latest]|join("/") }}'
                dest: '{{ item.0.1.prefix|default("") ~ latest|splitext|first }}.qcow2'
          vars:
            base: '{{ item.0.1.url if item.0.1.url|last == "/" else item.0.1.url|dirname }}'
            sixfour: '{{ item.1.content.splitlines()|select("search", "(amd64|x86_64)", ignorecase=true)|join("\n") }}'
            latest: '{{ sixfour|regex_findall(regex, ignorecase=true)|sort|last|regex_replace("\*", "") }}'
          loop: '{{ distros|dictsort|zip(checksums.results) }}'
          loop_control:
            label: '{{ item.0 }}'

    - get_url:
        url: '{{ item.src }}'
        dest: /mnt/data/cloudimg/{{ item.dest }}
      loop: '{{ q("vars", *q("varnames", "^img_url_.+")) }}'
