[ansibledev]
children = [
    "discovery",
]

[noc]
children = [
    "porky",
    "vpn",
    "binars",
]

[overseer]
children = [
    "porky",
    "locutus",
]

[ansibledev.hosts]
"sivel.eng.ansible.com" = { skip_docker_install = true }

[locutus.hosts]
"locutus.sivel.net" = {}

[riogrande.hosts]
"riogrande.sivel.net" = { ansible_host = "18.188.88.174" }

[porky.hosts."porky.noc.sivel.net"]
skip_docker_install = true
docker = false
proxmox = true

[wireguard]
children = [
    "vpn",
]

[vpn.hosts]
"vpn.noc.sivel.net" = { proxmox = true }

[vivo.hosts]
"vivo.noc.sivel.net" = {}

[binars.hosts]
"binars.noc.sivel.net" = {}

[nas.hosts]
"nas.noc.sivel.net" = { ansible_python_interpreter = "/usr/local/bin/python3", ansible_scp_if_ssh = true }

[unmanaged]
children = [
    "vivo",
    "nas",
]
