---
- hosts: locutus
  tasks:
    - import_role:
        role:
          name: caddy_v2
          caddyfile: "{{ playbook_dir }}/files/locutus/Caddyfile.v2"
      become: true
      tags:
        - caddy

    - import_role:
        role:
          name: weechat
      tags:
        - weechat

    - import_role:
        role:
          name: mosh
      become: true
      tags:
        - mosh
