- hosts: vivo
  gather_facts: false
  tasks:
    - find:
        paths: /mnt/data/bento/builds
        recurse: yes
        patterns: '*.qcow2'
      register: qcow2

    - add_host:
        name: '{{ name }}'
        qcow2: '{{ item.path }}'
        groups:
          - templates
      loop: '{{ qcow2.files }}'
      loop_control:
        label: '{{ name }}'
      vars:
        name: '{{ item.path|basename|splitext|first|replace("_", "-") }}'

- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: password
      prompt: Proxmox password
  tasks:
    - uri:
        url: https://vivo.noc.sivel.net:8006/api2/json/access/ticket
        validate_certs: false
        method: POST
        body:
          username: root@pam
          password: '{{ password }}'
        body_format: form-urlencoded
      no_log: true
      register: ticket
      delegate_to: localhost
      run_once: true

    - module_defaults:
        uri:
          headers:
            cookie: "PVEAuthCookie={{ ticket.json.data.ticket }}"
            CSRFPreventionToken: '{{ ticket.json.data.CSRFPreventionToken }}'
          validate_certs: false
      block:
        - uri:
            url: https://vivo.noc.sivel.net:8006/api2/json/nodes/vivo/qemu
          register: vms
          delegate_to: localhost
          run_once: true

        - set_fact:
            vmid: '{{ (vms.json.data|selectattr("name", "eq", item)|default([{"vmid": omit}], true)|first)["vmid"] }}'
          loop: '{{ groups.templates }}'
          delegate_to: '{{ item }}'
          delegate_facts: true

        - set_fact:
            missing: '{{ hostvars|dictsort|selectattr("0", "in", groups.templates)|selectattr("1.vmid", "undefined")|map(attribute="0")|sort }}'
            existing: '{{ vms.json.data|map(attribute="vmid")|map("int") }}'
          run_once: true

        - set_fact:
            id_map: '{{ dict(missing|sort|zip(pool)) }}'
          vars:
            pool: '{{ range(101, 1000)|list|difference(existing)|sort }}'
          run_once: true

        - add_host:
            name: '{{ item }}'
            vmid: '{{ id_map[item] }}'
            groups:
              - missing
          loop: '{{ missing }}'

- hosts: missing
  gather_facts: false
  module_defaults:
    uri:
      headers:
        cookie: "PVEAuthCookie={{ hostvars.localhost.ticket.json.data.ticket }}"
        CSRFPreventionToken: '{{ hostvars.localhost.ticket.json.data.CSRFPreventionToken }}'
      validate_certs: false
  tasks:
    - uri:
        url: https://vivo.noc.sivel.net:8006/api2/json/nodes/vivo/qemu
        method: POST
        body:
          name: '{{ inventory_hostname }}'
          vmid: '{{ vmid }}'
          cores: 2
          memory: 2048
          balloon: 2048
          scsihw: virtio-scsi-pci
          net0: 'bridge=vmbr0,model=virtio,firewall=1'
          agent: 'enabled=1'
        body_format: form-urlencoded
      delegate_to: localhost
      throttle: 2
      changed_when: true

    - command: qm importdisk {{ vmid }} {{ qcow2 }} data2
      become: true
      delegate_to: vivo
      throttle: 1

    - delegate_to: localhost
      block:
        - uri:
            url: https://vivo.noc.sivel.net:8006/api2/json/nodes/vivo/qemu/{{ vmid }}/config
            method: PUT
            body:
              scsi0: 'data2:vm-{{ vmid }}-disk-0,size=64G'
              bootdisk: scsi0
            body_format: form-urlencoded
          changed_when: true

        - uri:
            url: https://vivo.noc.sivel.net:8006/api2/json/nodes/vivo/qemu/{{ vmid }}/template
            method: POST
          delegate_to: localhost
          changed_when: true
