- hosts: localhost
  gather_facts: true
  vars:
    packages:
      - name: autoconf
        url: http://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.xz
      - name: automake
        url: http://ftpmirror.gnu.org/automake/automake-1.16.5.tar.xz
      - name: libtool
        url: http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
      - name: m4
        url: http://ftpmirror.gnu.org/m4/m4-1.4.19.tar.xz
      - name: pkg-config
        url: https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
        extra_configure: --with-internal-glib
        environment:
          LDFLAGS: "-framework CoreFoundation -framework Carbon $LDFLAGS"
      - name: gettext
        url: http://ftpmirror.gnu.org/gettext/gettext-0.21.tar.gz
      - name: libyaml
        url: http://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz
      # - name: zlib
      #   url: https://zlib.net/zlib-1.2.11.tar.xz
      - name: gmp
        url: https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz
      - name: nettle
        url: http://ftpmirror.gnu.org/nettle/nettle-3.7.3.tar.gz
        extra_configure: --build=aarch64-apple-darwin{{ ansible_facts.distribution_major_version }}
      - name: libunistring
        url: http://ftpmirror.gnu.org/libunistring/libunistring-1.0.tar.xz
      - name: libtasn1
        url: http://ftpmirror.gnu.org/libtasn1/libtasn1-4.18.0.tar.gz
      - name: gnutls
        url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.16.tar.xz
        extra_configure: --with-included-libtasn1 --without-p11-kit
      - name: pcre
        url: https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2/download
        filename: pcre-8.45.tar.bz2
      - name: lzma
        url: https://tukaani.org/xz/xz-5.2.5.tar.xz
      - name: wget
        url: http://ftpmirror.gnu.org/wget/wget-1.21.2.tar.lz
      - name: tar
        url: http://ftpmirror.gnu.org/tar/tar-1.34.tar.xz
        extra_configure: --program-prefix=g
      - name: sed
        url: http://ftpmirror.gnu.org/sed/sed-4.8.tar.xz
        extra_configure: --program-prefix=g
      - name: the_silver_searcher
        url: https://geoff.greer.fm/ag/releases/the_silver_searcher-2.2.0.tar.gz
      - name: tig
        url: https://github.com/jonas/tig/releases/download/tig-2.5.4/tig-2.5.4.tar.gz
      # - name: glib
      #   url: https://download.gnome.org/sources/glib/2.71/glib-2.71.0.tar.xz
      #   configure: meson --prefix={{ prefix }} _build
      #   make: ninja -C _build
      #   make_install: ninja -C _build install
      # - name: pixman
      #   url: https://cairographics.org/releases/pixman-0.40.0.tar.gz
      # - name: qemu
      #   url: https://download.qemu.org/qemu-6.2.0.tar.xz
      #   extra_configure: --target-list=x86_64-softmmu,aarch64-softmmu
      # - name: libusb
      #   url: https://github.com/libusb/libusb/releases/download/v1.0.25/libusb-1.0.25.tar.bz2
      - name: blueutil
        url: https://github.com/toy/blueutil/archive/v2.9.0.tar.gz
        make_install: false
        configure: false
        tarball_prefix: blueutil-
        bin_path: blueutil
      - name: htop
        url: https://github.com/htop-dev/htop/releases/download/3.2.0/htop-3.2.0.tar.xz
      - name: libxcrypt
        url: https://github.com/besser82/libxcrypt/releases/download/v4.4.28/libxcrypt-4.4.28.tar.xz
      - name: protobuf
        url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.2.tar.gz
        tarball_prefix: protobuf-
        pre_configure: ./autogen.sh
        environment:
          CXXFLAGS: -std=c++11
      - name: mosh
        url: https://mosh.org/mosh-1.3.2.tar.gz
        pre_configure: ./autogen.sh
        patches:
          - url: https://raw.githubusercontent.com/macports/macports-ports/72fb5d9a79e581a5033bce38fb00ee25a0c2fdfe/net/mosh/files/patch-version-subdir.diff
            strip: 0
          - url: https://github.com/mobile-shell/mosh/commit/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch?full_index=1
        environment:
          CXXFLAGS: -std=c++11
      - name: sshpass
        url: https://downloads.sourceforge.net/project/sshpass/sshpass/1.08/sshpass-1.08.tar.gz
    prefix: '{{ ansible_facts.env.HOME }}'
  tasks:
    - include_role:
        name: install_c_src_pkg
        apply:
          become: false
          tags:
            - '{{ package.name }}'
      loop: '{{ packages }}'
      loop_control:
        loop_var: package
      tags:
        - always
