---
- name: Remove the root users ssh key
  file:
    path: /root/.ssh/authorized_keys
    force: yes
    state: absent

- name: Remove unwanted users
  user:
    name: '{{ item }}'
    state: absent
    remove: yes
  loop:
    - ubuntu
    - vagrant
    - pi

- name: Remove various bento files
  file:
    path: '{{ item }}'
    state: absent
    force: yes
  loop:
    - /etc/sudoers.d/vagrant
    - /etc/sudoers.d/99_vagrant
    - /etc/update-motd.d/99-bento
    - /etc/polkit-1/rules.d/49-vagrant.rules
