- file:
    path: ~/projects/ansibledev
    state: directory

- git:
    repo: git@github.com:sivel/ansible.git
    dest: ~/projects/ansibledev/ansible
    update: no
    accept_hostkey: yes

- include_tasks:
    file: venv.yml
  loop: "{{ ansibledev_venvs }}"

# - command: nohup docker pull -a ansible/ansible
#   async: 3600
#   poll: 0
