- file:
    path: ~/projects/ansibledev
    state: directory

- git:
    repo: git@github.com:sivel/ansible.git
    dest: ~/projects/ansibledev/ansible
    update: no

- shell: source .profile && mkvirtualenv -p ~/.pyenv/versions/3.6.5/bin/python -a ~/projects/ansibledev ansibledev
  args:
    creates: ~/venvs/ansibledev
  register: ansibledev

- shell: ~/venvs/ansibledev/bin/pip install -r ~/projects/ansibledev/ansible/requirements.txt -r ~/projects/ansibledev/ansible/test/runner/requirements/ansible-test.txt argcomplete
  when: ansibledev is changed

- shell: source .profile && mkvirtualenv -p ~/.pyenv/versions/2.7.14/bin/python -a ~/projects/ansibledev ansibledev2
  args:
    creates: ~/venvs/ansibledev2
  register: ansibledev2

- shell: ~/venvs/ansibledev/bin/pip install -r ~/projects/ansibledev/ansible/requirements.txt -r ~/projects/ansibledev/ansible/test/runner/requirements/ansible-test.txt argcomplete
  when: ansibledev2 is changed

# - command: nohup docker pull -a ansible/ansible
#   async: 3600
#   poll: 0
