- name: Create virtualenv
  shell: source ~/.profile && mkvirtualenv -p ~/.pyenv/versions/{{ item.python }}/bin/python -a ~/projects/ansibledev {{ item.name }}
  args:
    creates: ~/venvs/{{ item.name }}
    executable: /bin/bash
  register: venv

- name: Install python deps
  shell: ~/venvs/{{ item.name }}/bin/pip install -r {{ ansible_path }}/requirements.txt argcomplete
  vars:
    ansible_path: "~/projects/ansibledev/ansible"
  when: venv is changed
