---
#eth0-dhcp   eth0-static.j2 interfaces  lo
- copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- copy:
    src: lo
    dest: /etc/network/interfaces.d/lo.cfg
    owner: root
    group: root
    mode: 0644

- copy:
    src: eth0-dhcp
    dest: /etc/network/interfaces.d/eth0.cfg
    owner: root
    group: root
    mode: 0644
  when: not eth0_static

- template:
    src: eth0-static.j2
    dest: /etc/network/interfaces.d/eth0.cfg
    owner: root
    group: root
    mode: 0644
  when: eth0_static
